//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuneRestaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartView
    {
        public int DishID { get; set; }
        public int CartID { get; set; }
        public string UserID { get; set; }
        public int Quantity { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public string Description_Short { get; set; }
    }
}
